version: '3.3'

services:
    lucee:
        image: lucee/lucee:latest
        environment:
          - LUCEE_JAVA_OPTS=-Xmx1024m
        volumes:
          - ./app:/var/www
          - type: bind
            source: ./lucee-admin-password/password.txt
            target: /opt/lucee/server/lucee-server/context/password.txt
        ports:
          - "8888:8888"
        # see readme for optional elements to set java options, copy in code, and/or set Lucee admin 
    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example
      volumes:
        - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
